### ISSUE TITLE
The Examples , Buttons view Errors in chrome.

### ISSUE THREAD

**Issue by madcid** [QiTASC/hatchinq#9]

**Comment by enrimilan** [comment]
I just tried the examples with Chrome (Ubuntu) and was not able to reproduce/didn't see any errors. Could you maybe be more specific what the error is? Thank you.

**Comment by madcid** [comment]
Now, That's OK.  I used archLinux .

**Comment by cloudshill** [comment]
Please help me ，
I don't understand how to use the Dropdown,  for searching suggestion 。
Thank you.
